# Generated by Django 5.1.6 on 2025-03-26 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebayaab', '0003_tarea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='completada',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='creado',
        ),
        migrations.AddField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En Curso'), ('completada', 'Completada')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
