# Generated by Django 5.1.6 on 2025-03-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebayaab', '0005_alter_tarea_fecha_vencimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_evento', models.DateTimeField()),
            ],
        ),
    ]
