# Generated by Django 5.1.6 on 2025-04-23 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebayaab', '0006_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodoOrganigrama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('puesto', models.CharField(max_length=100)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='pruebayaab.nodoorganigrama')),
            ],
        ),
    ]
